- task: SonarQubePrepare@5
  inputs:
    scannerMode: 'MSBuild'
    projectKey: 'sqa_2cc9eec94fec692108d4021bae1e7de31da76980'
    projectName: 'CI_CD_PIPELINE_01'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME'
